// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addy.proto

/*
Package addy is a generated protocol buffer package.

It is generated from these files:
	addy.proto

It has these top-level messages:
	NumbersToAdd
	Sum
*/
package addy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NumbersToAdd struct {
	A int32 `protobuf:"varint,1,opt,name=a" json:"a,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=b" json:"b,omitempty"`
}

func (m *NumbersToAdd) Reset()                    { *m = NumbersToAdd{} }
func (m *NumbersToAdd) String() string            { return proto.CompactTextString(m) }
func (*NumbersToAdd) ProtoMessage()               {}
func (*NumbersToAdd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NumbersToAdd) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *NumbersToAdd) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type Sum struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *Sum) Reset()                    { *m = Sum{} }
func (m *Sum) String() string            { return proto.CompactTextString(m) }
func (*Sum) ProtoMessage()               {}
func (*Sum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Sum) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*NumbersToAdd)(nil), "addy.NumbersToAdd")
	proto.RegisterType((*Sum)(nil), "addy.Sum")
}

func init() { proto.RegisterFile("addy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4c, 0x49, 0xa9,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xb4, 0xb8, 0x78, 0xfc, 0x4a,
	0x73, 0x93, 0x52, 0x8b, 0x8a, 0x43, 0xf2, 0x1d, 0x53, 0x52, 0x84, 0x78, 0xb8, 0x18, 0x13, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x18, 0x13, 0x41, 0xbc, 0x24, 0x09, 0x26, 0x08, 0x2f, 0x49,
	0x49, 0x96, 0x8b, 0x39, 0xb8, 0x34, 0x57, 0x48, 0x8c, 0x8b, 0xad, 0x28, 0xb5, 0xb8, 0x34, 0xa7,
	0x04, 0xaa, 0x0e, 0xca, 0x33, 0xd2, 0xe7, 0x62, 0x05, 0x9a, 0x90, 0x5a, 0x24, 0xa4, 0xc6, 0xc5,
	0x0c, 0x32, 0x4a, 0x48, 0x0f, 0x6c, 0x1b, 0xb2, 0xf1, 0x52, 0x9c, 0x10, 0x31, 0xa0, 0x31, 0x4a,
	0x0c, 0x49, 0x6c, 0x60, 0x87, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xdb, 0x0e, 0xf0,
	0x96, 0x00, 0x00, 0x00,
}
